Create linters.yml
Mounir-kh/hello-microverse pull request #1
Opened 2022-04-21 19:53 UTC by Mounir-kh

linters created

2022-04-21 23:20 UTC, koomekevo requested changes
Hi @Mounir-kh, 

<img src="https://media2.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
:heavy_check_mark: Your project has no linter errors.
:heavy_check_mark: Your README is descriptive. 

## Required Changes ♻️
_Check the comments under the review._

- [x] Kindly make your PR descriptive by adding a descriptive title and short summary of what the PR aims to do.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 23:20 UTC, koomekevo commented on .gitignore
> +
@Mounir-kh kindly add test.md file to the .gitignore as a project requirement.

2022-04-22 08:35 UTC, Mounir-kh commented
Thank you for your review, I appreciate

2022-04-22 09:28 UTC, Lucas-Masaba approved these changes
Hello @Mounir-kh 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._


- [ ] Good job implementing the README 👍 . However, it is the default template with default values. Please modify your README to include the right project name(Hello Microverse), tools, your personal author information and so on. Please work on this as it is a core requirement

- [ ] You are missing the test.md as described in the project [requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) as seen here 
![image](https://user-images.githubusercontent.com/45460192/164677634-7ccfb03b-c9e5-438a-9ea6-4c692bcd842d.png)
I will approve this project but please work on these as they are core requirements 👍 😄

2022-04-22 09:44 UTC, merged